# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsComing' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewsComing
  
  pod 'Masonry', '~> 1.0.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MJExtension', '~> 3.0.13'
  pod 'FMDB', '~> 2.6.2'
  pod 'CocoaLumberjack', '~> 2.3.0'
  pod 'MBProgressHUD', '~> 0.9'
  pod 'Shimmer', '~> 1.0.0'
  pod 'FlatUIKit', '~> 1.6.2'
  pod 'RESideMenu', '~> 4.0.7'
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'MWPhotoBrowser', '~> 2.1.0'
  pod 'CYLTabBarController', '~> 1.6.0'
  pod 'BmobSDK', '~> 1.7.2'
  pod 'WMPageController', '~> 1.8.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'TPKeyboardAvoiding', '~> 1.3'
 
end
